// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Models;

namespace Server.Migrations
{
    [DbContext(typeof(StudentsContext))]
    partial class StudentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AKITE.Contingent.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GroupID");

                    b.Property<int?>("GroupNum");

                    b.Property<int>("SpecialtyId");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AKITE.Contingent.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.Property<string>("ShortName");

                    b.HasKey("Id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("AKITE.Contingent.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AddressesIdentical");

                    b.Property<string>("AttNum");

                    b.Property<float?>("AverageGrade");

                    b.Property<DateTime?>("Birthday");

                    b.Property<int?>("CaseNum");

                    b.Property<string>("CertNum");

                    b.Property<string>("City");

                    b.Property<DateTime>("CreationDate");

                    b.Property<int?>("Degree");

                    b.Property<string>("Education");

                    b.Property<string>("Email");

                    b.Property<string>("FacticalCity");

                    b.Property<string>("FacticalFlatNum");

                    b.Property<string>("FacticalHouse");

                    b.Property<string>("FacticalRegion");

                    b.Property<string>("FacticalStreet");

                    b.Property<string>("FirstName");

                    b.Property<string>("FlatNum");

                    b.Property<int?>("Gender");

                    b.Property<int>("GroupIndex");

                    b.Property<string>("House");

                    b.Property<string>("Language");

                    b.Property<string>("LastName");

                    b.Property<string>("MidName");

                    b.Property<DateTime?>("PassportDate");

                    b.Property<string>("PassportNumber");

                    b.Property<string>("PassportPlace");

                    b.Property<int?>("PassportType");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Region");

                    b.Property<string>("Street");

                    b.Property<int?>("StudyForm");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
